apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-kafka-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-kafka-operator
  template:
    metadata:
      labels:
        name: knative-kafka-operator
    spec:
      serviceAccountName: knative-kafka-operator
      containers:
        - name: knative-kafka-operator
          # Replace this with the built image name
          image: quay.io/openshift-knative/knative-kafka-operator:v0.6.0
          command:
          - knative-kafka-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knative-kafka-operator"
